name: 🔨 Build Test

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.go'
      - '**.mod'
      - '**.sum'
  pull_request:
    paths:
      - '**.go'
      - '**.mod'
      - '**.sum'
  workflow_dispatch:

jobs:
  build:
    name: Test Builds
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Go Mod hygiene
        if: matrix.os == 'ubuntu-latest'
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum

      - name: Build
        run: go build .
        working-directory: cmd/dnshunter/

      - name: Test
        run: go test ./...

      - name: Race Test
        if: matrix.os == 'ubuntu-latest'
        run: go test -race ./...
